### ISSUE TITLE
Organization creation page timezone is marked as compulsory but user can sign up without entering a value

### ISSUE THREAD

**Issue by kunaltarcar** [ajency/Dilbert3.0#1]
Browser: Chrome
On the website creation page, the timezone should be a compulsory value, but user can signup without entering any value.
Steps to recreate the bug:
1. Sign in to dilbert with a new domain. On the organization page, leave the timezone blank with no value. 
2.Click on create Organization

Expected outcome: Error message saying enter timezone
Actual Outcome: User can sign in without specifying timezone.

**Comment by SharathSkN** [comment]
Handled the issue
