### ISSUE TITLE
App activity log when the system loses a working internet connection.

### ISSUE THREAD

**Issue by kunaltarcar** [ajency/Dilbert3.0#10]
Steps:
1. Log in and stay active.
2. Go into airplane mode.

Expected outcome: App should go offline, and display this message once the connection is restored.
Actual outcome: No change of state is recorded during the duration when there is no connection.

**Comment by SharathSkN** [comment]
Done - Changes state to offline

**Comment by SharathSkN** [comment]
Fixed the issue

**Comment by SharathSkN** [comment]
Using AJAX request, fetches the total time from Server
