### ISSUE TITLE
Edit profile Page - UI not intuitive

### ISSUE THREAD

**Issue by kunaltarcar** [ajency/Dilbert3.0#11]
On the edit Profile page, the editable fields appear to be static/read-only due to an absence of any call to action.
It should be intimated to the user that those fields are editable, using some sort of marker.

![image](https://cloud.githubusercontent.com/assets/20510907/18464621/bf492840-79af-11e6-9bf2-d111ca4ce468.png)

**Comment by renukaajency** [comment]
Done
