### ISSUE TITLE
Untranslated words

### ISSUE THREAD

**Issue by kunaltarcar** [ajency/Dilbert3.0#12]
On the Login page, the "Sign Up" link is not translated.
![image](https://cloud.githubusercontent.com/assets/20510907/18465376/1985f776-79b4-11e6-83c2-543902f3a064.png)

Organization page, "Logo" label is not translated.
Organization page, "Organization" label is not translated.
![image](https://cloud.githubusercontent.com/assets/20510907/18465648/5bbbfdba-79b5-11e6-9646-6ee757ef3648.png)

**Comment by SharathSkN** [comment]
Done
