### ISSUE TITLE
View Organization Page Logo size issue in firefox

### ISSUE THREAD

**Issue by kunaltarcar** [ajency/Dilbert3.0#3]
Browser: Firefox, Edge

Once logged in, in the View Organizations page, the size of the logo is disproportionately large. It does not resize.
Steps:
1. Sign in, and go to the View Organizations page.

Expected Outcome: The retrieved logo should resize to fit the table
Actual outcome: The logo does not resize and is disproportionately large.

**Comment by SharathSkN** [comment]
Fixed
