### ISSUE TITLE
App Activity Log issue when system sleeps before the app goes idle.

### ISSUE THREAD

**Issue by kunaltarcar** [ajency/Dilbert3.0#7]
When the system sleeps before the app goes idle, ideally the app should record a change of state from active to idle/offline as decided.
Steps:
1. Log in and stay active. Setup sleep time to say x minutes.
2. App idle time should be set to x+1 at the very least.
3. Leave the system idle for greater than x+1 minutes, and then wake the system again.

Expected outcome: App records a single change of state from Active to idle/offline, and then back to Active.
Actual Outcome: App does not record or display a change of state to idle/offline, and instead the change to Active is displayed twice.

**Comment by SharathSkN** [comment]
Change in plans & structure
