### ISSUE TITLE
Activity Log display when System shuts down while app is active

### ISSUE THREAD

**Issue by kunaltarcar** [ajency/Dilbert3.0#8]
Steps:
1. Sign in and stay idle until change of state to idle is recorded.
2. Using the power button, shut down the system without affecting the status.
3. Reboot and sign into the app.
4. Observe the Activity Log.

Expected outcome: Change of state from idle to offline and the active when user logs in again.
Actual outcome: Does not display the offline message. Instead the Active state is indicated twice.

**Comment by SharathSkN** [comment]
Fixed. I guess :p
